pool:
  vmImage: 'windows-2022'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  productName: 'RegionToShare'

steps:
- task: PowerShell@1
  displayName: 'Set build version'
  inputs:
    scriptType: inlineScript
    inlineScript: |
        (new-object Net.WebClient).DownloadString("https://raw.github.com/tom-englert/BuildScripts/master/BuildScripts.ps1") | iex
        $version = Project-SetVersion "src\Directory.Build.props"
        $version | Build-AppendVersionToBuildNumber
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: CopyFiles@2
  inputs:
    Contents: '**/bin/$(buildConfiguration)/**/*.exe*'
    TargetFolder: '$(build.artifactstagingdirectory)/$(productName)'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(productName)'
    ArtifactName: 'bin'
    publishLocation: 'Container'
